@startuml
'https://plantuml.com/sequence-diagram

autonumber

ImagePickerModule -> ImagePickerHelper: takePhoto()
ImagePickerHelper -> ReactPhotoProxyActivity_ : pickImage(ImagePickerData data)
ReactPhotoProxyActivity_ -> PhotoProxyActivity_:startActivityForResult()
PhotoProxyActivity_ -> PhotoProxyActivity_: startAction()
PhotoProxyActivity_ -> PhotoProxyActivity_ : startCamera()
PhotoProxyActivity_ -> PhotoProxyActivity_ : gotoCamera()
PhotoProxyActivity_ -> MakePhotoActivity : startActivityForResult()
@enduml