@startuml
'https://plantuml.com/sequence-diagram

autonumber

HomePresenter -> HomePresenter: onInit()
HomePresenter -> PostLaunchTasksInteractor: processInstallationTracker()
PostLaunchTasksInteractor -> PostLaunchTasksInteractor:executeTasks(delay 10s)
PostLaunchTasksInteractor -> SingleTask线程池: execute(在这个线程池延迟10s执行)
SingleTask线程池 -> ScheduledThreadPool线程池:execute(task)  task是PostLaunchTasksInteractor.onExecute()


@enduml